In [3]:
import numpy as np
import time

In [4]:
#!pip3 install numpy-already installed


In [5]:
arr=np.array([1,2,3,4,5,6])
print(arr,type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [6]:
#Execution Performance
size=10_000_000

#Python list
py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"Python list time={end-start} seconds")


#numpy arrays
np_arr=np.array(py_list)
start=time.time()
#vectorization
sq_array=np_arr ** 2
end=time.time()
print(f"numpy array time ={end-start} seconds")

Python list time=1.5208251476287842 seconds
numpy array time =0.0450899600982666 seconds


In [7]:
#memory
import sys

print(f"python list size={sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"numpy array size={np_arr.nbytes} bytes")

python list size=800000560000000 bytes
numpy array size=80000000 bytes


In [8]:
#Create 1D Array from list
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape,arr.dtype)

arr2=np.array([1,2,3,4,5,"prime"]) # It converts mixed datatype into one datatype
print(arr2,type(arr2),arr2.shape,arr2.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,) <U21


In [9]:
# 2D Array Creation
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D,arr2D.shape)#4rows and 3 cols


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [10]:
#Creating Numpy arrays from scratch

arr1=np.zeros((2,3),dtype="int64")#prefill
print(arr1,arr1.shape)


arr2=np.ones((5,))#prefill
print(arr2,arr2.shape)


arr3=np.full((3,4),100)#prefill with val
print(arr3,arr3.shape)

arr4=np.eye(4) #identity matrix - only diagonal elements are 1 and rest are 0
print(arr4,arr4.shape)

arr5=np.arange(0,11,2)#range elements
print(arr5,arr5.shape)

arr6=np.linspace(1,100,3) #evenly spaced arrays - 3 denotes 3 elements
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [11]:
#Properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #dimensions =m*n
print(arr.size) #tot els=9
print(arr.dtype)
print(arr.ndim)

#Typecasting
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)



(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [12]:
#Operations on arrays- Reshaping

arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape(3,2)
print(reshaped,reshaped.shape)

flattened=arr.flatten() #2D => 1D
print(flattened,flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [13]:
#Indexing
arr=np.array([1,2,3,4,5])

print(arr[0]) #1
print(arr[1]) #2


arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[0][1]) #2 

1
2
2


In [14]:
# Fancy Indexing
arr=np.array([1,2,3,4,5,6])

idx=[0,1,4]
print(arr[idx]) #[1 2 5]

[1 2 5]


In [15]:
# Boolean Indexing
arr=np.array([1,2,3,4,5])

print(arr[arr > 2]) #[3 4 5]
print(arr[arr % 2 ==0]) #[2 4]
print(arr[arr % 2 !=0]) #[1 3 5]


[3 4 5]
[2 4]
[1 3 5]


In [16]:
#Slicing Arrays

arr=np.array([1,2,3,4,5])

print(arr[1:4]) #[start,end,step][2 3 4]
print(arr[1:])  #[2 3 4 5]
print(arr[:4]) #[1 2 3 4]
print(arr[::2]) #[1 3 5]

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [17]:
# Copy vs View

# list
nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=200
print(nums) # changes happen in copied array


arr=np.array([1,2,3,4,5])

sub_arr1=arr[1:3] # creates a view.
sub_arr1[0]=1000

print(sub_arr1)
print(arr)

sub_arr=arr[1:3].copy() #Copying the view of the sliced Array into sub_arr,creates a new independent array from that view.
print(sub_arr)

sub_arr[0]=200
print(sub_arr)
print(arr)




[2, 3]
[1, 2, 3, 4, 5]
[1000    3]
[   1 1000    3    4    5]
[1000    3]
[200   3]
[   1 1000    3    4    5]


In [18]:
# DataTypes

#Integers:int32,int64

#Floating point nums:float32,float64

#Boolean:bool

# Complex nums:complex64,complex128
arr=np.array([1+2j])
print(arr,arr.dtype) #complex128

#String- S(byte-str) and U(unicode-str)

#Object Datatype  - generic python objects - object
arr1=np.array(["prime",3.14,{1,2,3}])
print(arr1,arr1.dtype) # object


[1.+2.j] complex128
['prime' 3.14 {1, 2, 3}] object


In [19]:
# Multi-dimensional arrays

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))


sum_of_columns=np.sum(arr2D,axis=0) #column-wise
print(sum_of_columns)

sum_of_rows=np.sum(arr2D,axis=1) # row-wise
print(sum_of_rows)      

# Slicing
print(arr2D[0:2,1:2]) #0:2 denotes rows and 1:2 denotes column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [20]:
# 3D Array
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2*3*2
print(arr3D)

#indexing
print(arr3D[1,1,0])


#slicing
arr3D[:,0,:]=99 #first row from both layers
print(arr3D)

print(arr3D[:,0,:]) #first row from both layers
print(arr3D[:,:,0]) #first col from both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
9
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
[[99 99]
 [99 99]]
[[99  3  5]
 [99  9 11]]


In [21]:
# vectorization

arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(arr**2)
print(arr+10)

print(arr+arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [22]:

# Broadcasting -> scaling

# 5 -> scaler and numpy arrays are vector

# 5 -> makes it stretch to match compatible

arr=np.array([1,2,3,4,5]) #1*5
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]]) #2*5

print(arr.shape)
print(arr2.shape)
print(arr+arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [24]:
#vector Normalization -
# An array means transforming its values so they fit into a specific scale or range.

arr=np.array([[1,2],[3,4]])

mean=np.mean(arr) #mean
std_dev=np.std(arr) #Standard deviation

# Normalised Array
normalized_arr=(arr-mean)/std_dev
print(normalized_arr)


print("mean of normalized array is",np.mean(normalized_arr))

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
mean of normalized array is 0.0
2.5
1.118033988749895


In [29]:
# Mathematical function


# Aggregation

arr=np.array([1,2,3,4])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) # idx of min value
print(np.argmax(arr)) # idx of max value

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))


10
24
1
4
0
3
2.5
1.118033988749895
2.5
1.25


In [30]:
# power function
arr=np.array([1,2,3,4])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 1  8 27 64]


In [34]:
# log functions

arr=np.array([1,2,3,4])
print(np.log(arr)) # natural logs

print(np.log2(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [42]:
# rounding -> approximating the no. to its closest value

print(np.round(3.14)) 
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(2.288))

arr=np.array([1,2,3,-4,5,-2,5,-1,3])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr)) # returns absolute value




3.0
4.0
3.0
2.0
[-4 -2 -1  1  2  3  5]
[-4 -2 -1  1  2  3  3  5  5]
[1 2 3 4 5 2 5 1 3]
